# odoo18-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo18-data
  namespace: odoo18
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo18-logs
  namespace: odoo18
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
